

```{r}
library(Seurat)
library(dplyr)
library(ggplot2)
library(usethis)
library(devtools)
library(harmony)
library(patchwork)
library(ggplot2)
library(gridExtra)
library(jcolors)
library(MetBrewer)
```


```{r}
setwd("/Users/jainak/polybox/Jain_Gut_et_al_2023/scRNAseq_analysis_data/2.Matrix_perturbation_scRNAseq_Day13")
seurat_Day13_matrix <- readRDS( "seurat_Day13_matrix_integrated.rds")
```


```{r}


plot1 <- UMAPPlot(seurat_Day13_matrix,group.by = "dataset", pt.size = 0.5, cols = c("#ACE6DF","#00BBA5", "#606060"))
plot1

plot2 <- UMAPPlot(seurat_Day13_matrix, label = T)
plot2

```

                              ####  cluster ids  ####
```{r}

Idents(seurat_Day13_matrix) <- "seurat_clusters"

# stash current cluster IDs
seurat_Day13_matrix[["cluster.ids"]] <- Idents(object = seurat_Day13_matrix)

# enumerate current cluster IDs and the labels for them
cluster.ids <- c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,12,13,14,15,16,17,18,19)

anno_class1 <- c("Telencephalic progenitors", #  0
            "non-telencephalic progenitors",#WLS  1
            "early neural progenitors1", #F   2
            "early neural progenitors1", #  VIM  3
            "early neural progenitors1",#WLS   4
            "non-telencephalic progenitors", # VIM    5
            "Telencephalic progenitors", #SOX2 PAX6 FOXG1 LHX2 SIX3    6
            "Telencephalic progenitors",#POU5F1 TCF7L2    7
            "non-telencephalic progenitors",#POU5F1 FOXD3 FOXO1   8
            "Telencephalic progenitors",#POU5F1 TCF7L2   9
            "Telencephalic progenitors", #DLX2 STMN2 DCX   10
            "Neural crest", #SOX2 PAX6 FOXG1 LHX2 SIX3    11
            "Neural crest", # VIM         12
            "non-telencephalic progenitors", # MKI67   13
            "Neural crest",        #   14
            "non-Tel neurons1", #    15
            "Pluripotent cells",   # POU5F1   16
            "Neural crest", #SOX10   17
            "early neural progenitors2",  # 18
            "non-Tel neurons2")#  

seurat_Day13_matrix@meta.data[,'anno_class1'] <- plyr::mapvalues(x = seurat_Day13_matrix@meta.data$cluster.ids, from = cluster.ids, to = anno_class1)

seurat_Day13_matrix$anno_class1 <- factor(seurat_Day13_matrix$anno_class1, levels = c("Telencephalic progenitors","non-telencephalic progenitors","early neural progenitors1","early neural progenitors2","Pluripotent cells","Neural crest","non-Tel neurons1","non-Tel neurons2"))


color_anno = c("#049983","#264653","#EFC159","#cc9933","#ee6a50","#f4a261","#a3b18a","#930707")


classdimplot <- DimPlot(seurat_Day13_matrix, reduction = "umap", pt.size = 0.5, label = F,order = F, group.by = 'anno_class1', cols = color_anno) & NoAxes()
classdimplot

```

#####   stacked plot
```{r}
library(dittoSeq)

Idents(seurat_Day13_matrix) -> "seurat_clusters"

seurat_Day13_matrix$anno_class1 <- factor(seurat_Day13_matrix$anno_class1, levels = c("Telencephalic progenitors","non-telencephalic progenitors","early neural progenitors1","early neural progenitors2","Pluripotent cells","Neural crest","non-Tel neurons1","non-Tel neurons2"))

seurat_Day13_matrix$dataset <- factor(seurat_Day13_matrix$dataset, levels = c("HB4 Mat Day 13", "HB4 NoMat Day 13", "HB4 Agar Day 13"))

barplot_conditions<-dittoBarPlot(
  object = seurat_Day13_matrix,
  var = "anno_class1",
  group.by = "dataset",
  color.panel = color_anno,
  retain.factor.levels = T,
  ylab = "Cluster proportion")
barplot_conditions


```
                    


```{r}
#Create a volcano plot for visualisation (or a heatmap would also work)
library(EnhancedVolcano)
library(dittoSeq)

Idents(seurat_Day13_matrix) <- "dataset"

cl_markers_mat.nomat <- FindMarkers(seurat_Day13_matrix, ident.1 =c("HB4 Mat Day 13"), ident.2 = c("HB4 NoMat Day 13"), only.pos = F)

volcano_1 <- EnhancedVolcano(cl_markers_mat.nomat,
                             lab = rownames(cl_markers_mat.nomat),
                             #selectLab = rownames(cl_markers_mat.nomat),
                             selectLab = c("WLS","EMX2","SIX3","SIX6","WNT4","RSPO3","PAX3","SFRP2","WNT2B","TFAP2A","SOX10","LHX2","POU5F1","SOX2","GPC3","HESX1","NRG1","LHX2","FJX1","IGFBP2","FGF8","FEZF1","FEZF2","FZD5","ZIC2","FAT1","FZD8"),
                             x = 'avg_log2FC',
                             y = 'p_val',
                             title = 'Mat vs NoMat D13',
                             pCutoff = 10e-3,
                             pCutoffCol = "p_val_adj",
                             FCcutoff = 0.5,
                             xlim = c(-2.5, 2.5),
                             pointSize = 3,
                             col=c("maroon3","purple4","grey60","black"),
                             drawConnectors = T)+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))+ theme(text = element_text(size = 8))    

volcano_1

write.csv(cl_markers_mat.nomat, "DE_genes_matVsnomat.csv")

```

                ##### create files for DAVID GO term analysis ########

```{r}


det_rates <- rowMeans(seurat_Day13_matrix[['RNA']]@data > 0)

detected_genes <- rownames(seurat_Day13_matrix)[which(det_rates > 0.01)]

res_DE <- FindMarkers(seurat_Day13_matrix, features = detected_genes, group.by = "dataset", ident.1 = "HB4 Mat Day 13", ident.2 = "HB4 NoMat Day 13")

DE_up_in_matrigel <- res_DE[res_DE$avg_log2FC > log(1.2),]
DE_down_in_matrigel <- res_DE[res_DE$avg_log2FC < -log(1.2),]


write.table(DE_up_in_matrigel, file="DE_up.tsv", quote=F, sep="\t", row.names=F, col.names=F)
write.table(DE_down_in_matrigel, file="DE_down.tsv", quote=F, sep="\t", row.names=F, col.names=F)

write.csv(DE_up_in_matrigel, file="DE_up.csv")
write.csv(DE_down_in_matrigel, file="DE_down.csv")

```

        ##save background genes for DAVID analysis##


```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("biomaRt")

library(biomaRt)

ensembl <- useEnsembl(biomart = "ensembl",
                      dataset = "hsapiens_gene_ensembl",
                      version = 93)
meta_genes <- getBM(attributes = c("ensembl_gene_id",
                                   "ensembl_gene_id_version",
                                   "hgnc_symbol",
                                   "description",
                                   "chromosome_name",
                                   "start_position",
                                   "end_position",
                                   "strand"),
                    filters = "hgnc_symbol",
                    values = rownames(seurat_Day13_matrix),
                    mart = ensembl) %>%
  right_join(data.frame(hgnc_symbol= rownames(seurat_Day13_matrix)),
             by = "hgnc_symbol") %>%
  distinct(hgnc_symbol, .keep_all = TRUE)

write.table(meta_genes$ensembl_gene_id[meta_genes$hgnc_symbol %in% detected_genes], file="background.tsv", quote=F, sep="\t", row.names=F, col.names=F)

result_data <- read.csv("up_DAVID_t2t_5957FDDF677B1674660059570.txt", header = TRUE, sep = "\t", col.names = NULL, )
```       
        
```{r}

saveRDS(seurat_Day13_matrix, "seurat_Day13_matrix_processed.rds")

```
          
                    

